### ISSUE TITLE
AttributeError: module 'escriptorium' has no attribute 'celery' on Ubuntu 20.04.6 after installation

### ISSUE THREAD

**Issue by centralcityinvestments** [UB-Mannheim/eScriptorium_Dokumentation#4]
Using the documentation I did the [Local installation (Windows/Linux)](https://ub-mannheim.github.io/eScriptorium_Dokumentation/Lokale_Installation_eScriptorium.html) but I have to admit that I didn't look for exactly Ubuntu 20.04.3 and instead installed the latest Ubuntu 20.04.6. 

After this line: DJANGO_SETTINGS_MODULE=escriptorium.local_settings celery -A escriptorium worker -l INFO &
There was the message:
```
Command 'celery' not found, but can be installed with:

sudo apt install python-celery-common
```
So I did the installation as suggested, run the command again, and then there is this message:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/celery/app/utils.py", line 365, in find_app
    found = sym.app
AttributeError: module 'escriptorium' has no attribute 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/celery", line 26, in <module>
    load_entry_point("celery", "console_scripts", "celery")()
  File "/usr/lib/python3/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/lib/python3/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python3/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python3/dist-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/lib/python3/dist-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/lib/python3/dist-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/lib/python3/dist-packages/celery/app/utils.py", line 370, in find_app
    found = sym.celery
AttributeError: module 'escriptorium' has no attribute 'celery'

```
Maybe I'm still missing something to be installed, but the whole celery is not mentioned in the documentation?

**Comment by centralcityinvestments** [comment]
I guess it's because I opened a new terminal :-)

Everything runs without errors after following step 19. Reuse

**Comment by stweil** [comment]
Yes, you gave the right answer to your own question.

I suggest to uninstall the Ubuntu package `python-celery-common` again. It is not needed, and maybe it can cause conflicts with the package which was installed with pip.
